steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "eu.gcr.io/evry-flaatten/go-hello-world:$SHORT_SHA", "apps/hello-world/"]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "eu.gcr.io/evry-flaatten/go-hello-world:$SHORT_SHA"]
  # get cluster credentials
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'apps'
    - '--zone=europe-west1-b'
    - '--project=evry-flaatten'

