steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "eu.gcr.io/evry-flaatten/go-hello-world:$SHORT_SHA", "apps/hello-world/"]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/evry-flaatten/go-hello-world:$SHORT_SHA"]
  # deploy container image to GKE
